import type { CollectionConfig } from 'payload'
import { adminOnly } from '../lib/access'

/**
 * Admin-internal mirror of Systembolaget's product catalog.
 *
 * Used as a pick-list when filling in `customWine` snapshots on Reviews,
 * TastingPlans, and UserWines. Never published — no public read, no
 * customer-facing routes, no sitemap entries.
 *
 * Schema strategy: a small set of indexed first-class columns for query/picker,
 * plus a `raw` jsonb column carrying the full upstream record. Upstream
 * (Systembolaget via C4illin's mirror) is known to change shape; this keeps us
 * resilient without migrations every time a field is added.
 */
export const SystembolagetProducts: CollectionConfig = {
  slug: 'systembolaget-products',
  labels: {
    singular: 'Systembolaget product',
    plural: 'Systembolaget products',
  },
  admin: {
    group: 'Wine Library',
    useAsTitle: 'searchTitle',
    defaultColumns: [
      'productNumber',
      'productNameBold',
      'producerName',
      'vintage',
      'price',
      'country',
      'categoryLevel1',
    ],
    description:
      'Imported Systembolaget catalog. Admin-internal pick-list. Not published.',
    listSearchableFields: [
      'productNumber',
      'productNameBold',
      'producerName',
      'searchTitle',
    ],
  },
  access: {
    read: adminOnly,
    create: adminOnly,
    update: adminOnly,
    delete: adminOnly,
  },
  fields: [
    // Identity
    {
      name: 'productNumber',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      admin: { description: "Systembolaget's stable product number (e.g. '7355')" },
    },
    {
      name: 'productNumberShort',
      type: 'text',
      admin: { position: 'sidebar' },
    },

    // Names
    {
      name: 'productNameBold',
      type: 'text',
      index: true,
      admin: { description: "Primary product name" },
    },
    { name: 'productNameThin', type: 'text' },
    {
      name: 'producerName',
      type: 'text',
      index: true,
    },
    { name: 'supplierName', type: 'text' },

    // Categorization
    { name: 'category', type: 'text' },
    {
      name: 'categoryLevel1',
      type: 'text',
      index: true,
      admin: { description: "Top-level category (e.g. 'Rött vin', 'Vitt vin')" },
    },
    { name: 'categoryLevel2', type: 'text' },
    { name: 'categoryLevel3', type: 'text' },
    { name: 'categoryLevel4', type: 'text' },
    { name: 'customCategoryTitle', type: 'text' },

    // Origin
    {
      name: 'country',
      type: 'text',
      index: true,
      admin: { description: "Country string from upstream (e.g. 'Frankrike')" },
    },
    { name: 'originLevel1', type: 'text' },
    { name: 'originLevel2', type: 'text' },

    // Wine specifics
    { name: 'vintage', type: 'number' },
    { name: 'alcoholPercentage', type: 'number' },
    { name: 'volume', type: 'number', admin: { description: 'Volume in ml' } },
    { name: 'volumeText', type: 'text' },
    { name: 'bottleText', type: 'text' },
    { name: 'packagingLevel1', type: 'text' },
    { name: 'seal', type: 'text' },
    { name: 'color', type: 'text' },
    { name: 'taste', type: 'textarea' },
    { name: 'usage', type: 'textarea' },

    // Price
    { name: 'price', type: 'number', admin: { description: 'Price in SEK' } },
    { name: 'recycleFee', type: 'number' },

    // Assortment / availability
    { name: 'assortment', type: 'text' },
    { name: 'assortmentText', type: 'text' },
    { name: 'isDiscontinued', type: 'checkbox', defaultValue: false },
    { name: 'isCompletelyOutOfStock', type: 'checkbox', defaultValue: false },
    { name: 'isTemporaryOutOfStock', type: 'checkbox', defaultValue: false },
    { name: 'isNews', type: 'checkbox', defaultValue: false },

    // Labels
    { name: 'isOrganic', type: 'checkbox', defaultValue: false },
    { name: 'isKosher', type: 'checkbox', defaultValue: false },
    { name: 'isEthical', type: 'checkbox', defaultValue: false },
    { name: 'ethicalLabel', type: 'text' },
    { name: 'isSustainableChoice', type: 'checkbox', defaultValue: false },
    { name: 'isClimateSmartPackaging', type: 'checkbox', defaultValue: false },

    // Media (URLs only; we never download bottle images)
    {
      name: 'imageUrl',
      type: 'text',
      admin: { description: 'Bottle image URL on Systembolaget CDN' },
    },
    {
      name: 'productUrl',
      type: 'text',
      admin: { description: 'systembolaget.se product page URL' },
    },

    // Search
    {
      name: 'searchTitle',
      type: 'text',
      index: true,
      admin: {
        description:
          "Denormalized 'name producer (vintage) — productNumber' string for fast search. Auto-generated by the import.",
      },
    },

    // Grapes as raw string array (Systembolaget's strings, not linked to our `grapes` collection)
    {
      name: 'grapes',
      type: 'json',
      admin: {
        description: "Grape strings from Systembolaget (array of strings).",
      },
    },

    // Full upstream record — resilience against upstream schema drift.
    // We index a small set of columns above; everything else lives here untouched.
    {
      name: 'raw',
      type: 'json',
      admin: {
        description:
          'Full upstream record. Carries fields we do not promote to typed columns.',
        readOnly: true,
      },
    },

    // Import bookkeeping
    {
      name: 'lastImportedAt',
      type: 'date',
      admin: {
        position: 'sidebar',
        readOnly: true,
        description: 'When this row was last touched by the importer.',
      },
    },
    {
      name: 'sourceCommitSha',
      type: 'text',
      admin: {
        position: 'sidebar',
        readOnly: true,
        description:
          'Upstream commit SHA (when known) of the data this row was imported from.',
      },
    },
  ],
  timestamps: true,
}
