import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Fix the schema contradiction that blocked deleting users via the Payload admin:
 *
 * 1. Four collections have user/host relationship fields whose FK was `ON DELETE
 *    SET NULL` even though the column was NOT NULL. The FK SET-NULL would fire
 *    on user delete, then trip the NOT NULL constraint, abort the transaction,
 *    and bubble up as `25P02 — current transaction is aborted`.
 *
 *    For these we drop NOT NULL (auto-generated by migrate:create after toggling
 *    `required: false` in the collection definitions). Their FK already does the
 *    right thing (SET NULL), so the order/transaction/subscription/session is
 *    preserved as an anonymized historical record.
 *
 * 2. Five "personal data" tables (enrollments, quiz_attempts, user_progress,
 *    user_wine_lists, user_wines) had the same SET-NULL-with-NOT-NULL paradox.
 *    For these the right policy is the opposite — the row is meaningless without
 *    its user, so we flip the FK to ON DELETE CASCADE and let it disappear with
 *    the user. The column stays NOT NULL.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    -- (1) Drop NOT NULL on FKs we want to preserve with anonymization
    ALTER TABLE "transactions" ALTER COLUMN "user_id" DROP NOT NULL;
    ALTER TABLE "subscriptions" ALTER COLUMN "user_id" DROP NOT NULL;
    ALTER TABLE "orders" ALTER COLUMN "user_id" DROP NOT NULL;
    ALTER TABLE "course_sessions" ALTER COLUMN "host_id" DROP NOT NULL;

    -- (2) Flip FKs to CASCADE on personal-data tables so they disappear with the user
    ALTER TABLE "enrollments" DROP CONSTRAINT IF EXISTS "enrollments_user_id_users_id_fk";
    ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

    ALTER TABLE "quiz_attempts" DROP CONSTRAINT IF EXISTS "quiz_attempts_user_id_users_id_fk";
    ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

    ALTER TABLE "user_progress" DROP CONSTRAINT IF EXISTS "user_progress_user_id_users_id_fk";
    ALTER TABLE "user_progress" ADD CONSTRAINT "user_progress_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

    ALTER TABLE "user_wine_lists" DROP CONSTRAINT IF EXISTS "user_wine_lists_user_id_users_id_fk";
    ALTER TABLE "user_wine_lists" ADD CONSTRAINT "user_wine_lists_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

    ALTER TABLE "user_wines" DROP CONSTRAINT IF EXISTS "user_wines_user_id_users_id_fk";
    ALTER TABLE "user_wines" ADD CONSTRAINT "user_wines_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    -- (1) Restore NOT NULL on the four columns
    ALTER TABLE "transactions" ALTER COLUMN "user_id" SET NOT NULL;
    ALTER TABLE "subscriptions" ALTER COLUMN "user_id" SET NOT NULL;
    ALTER TABLE "orders" ALTER COLUMN "user_id" SET NOT NULL;
    ALTER TABLE "course_sessions" ALTER COLUMN "host_id" SET NOT NULL;

    -- (2) Revert FKs to SET NULL
    ALTER TABLE "enrollments" DROP CONSTRAINT IF EXISTS "enrollments_user_id_users_id_fk";
    ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

    ALTER TABLE "quiz_attempts" DROP CONSTRAINT IF EXISTS "quiz_attempts_user_id_users_id_fk";
    ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

    ALTER TABLE "user_progress" DROP CONSTRAINT IF EXISTS "user_progress_user_id_users_id_fk";
    ALTER TABLE "user_progress" ADD CONSTRAINT "user_progress_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

    ALTER TABLE "user_wine_lists" DROP CONSTRAINT IF EXISTS "user_wine_lists_user_id_users_id_fk";
    ALTER TABLE "user_wine_lists" ADD CONSTRAINT "user_wine_lists_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

    ALTER TABLE "user_wines" DROP CONSTRAINT IF EXISTS "user_wines_user_id_users_id_fk";
    ALTER TABLE "user_wines" ADD CONSTRAINT "user_wines_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION;
  `)
}
